### ISSUE TITLE
Remove all instances `$this->logger`

### ISSUE THREAD

**Issue by concept-core** [concept-core/laraslim#9]
This is being called in the controllers and if the config is said to not be enabled the app crashed.

**Comment by rayoriz** [comment]
I would work on this :)

**Comment by concept-core** [comment]
Go ahead :)

**Comment by rayoriz** [comment]
Ok just commented all instances across the files. Please check and merge if ok. Thanks.

**Comment by concept-core** [comment]
@rayoriz check comment on pr.
